// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDg_4pqv1vA-sMujNoAQvxer3e1IA_14Ig',
    appId: '1:324550194830:web:eb0d553e09da0df7e1fbdf',
    messagingSenderId: '324550194830',
    projectId: 'flutter-firebase-codelab-4ac2c',
    authDomain: 'flutter-firebase-codelab-4ac2c.firebaseapp.com',
    storageBucket: 'flutter-firebase-codelab-4ac2c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2hU6-6QIfLxIHAn1anmrBWPfHfl7XgIg',
    appId: '1:324550194830:android:24926cd7cfba4f39e1fbdf',
    messagingSenderId: '324550194830',
    projectId: 'flutter-firebase-codelab-4ac2c',
    storageBucket: 'flutter-firebase-codelab-4ac2c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArXnE4kay8pagbM6jhErcoldwlw_HOqaE',
    appId: '1:324550194830:ios:0d113bd99bc2b498e1fbdf',
    messagingSenderId: '324550194830',
    projectId: 'flutter-firebase-codelab-4ac2c',
    storageBucket: 'flutter-firebase-codelab-4ac2c.firebasestorage.app',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArXnE4kay8pagbM6jhErcoldwlw_HOqaE',
    appId: '1:324550194830:ios:0d113bd99bc2b498e1fbdf',
    messagingSenderId: '324550194830',
    projectId: 'flutter-firebase-codelab-4ac2c',
    storageBucket: 'flutter-firebase-codelab-4ac2c.firebasestorage.app',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
