// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1a5oWnkM-K2-Qa6e81E-jzKKx0dFm4VQ',
    appId: '1:977177627097:web:9814ea9982af86ef94b1c8',
    messagingSenderId: '977177627097',
    projectId: 'moap-final',
    authDomain: 'moap-final.firebaseapp.com',
    storageBucket: 'moap-final.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDW3h2jUHsy3gfOlba4zf6VOdLk6I-O3DA',
    appId: '1:977177627097:android:d82e3b848094048494b1c8',
    messagingSenderId: '977177627097',
    projectId: 'moap-final',
    storageBucket: 'moap-final.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBKE_74qMhZvyMN9o37cBGTCIee_xm254',
    appId: '1:977177627097:ios:c6ddb2506334568094b1c8',
    messagingSenderId: '977177627097',
    projectId: 'moap-final',
    storageBucket: 'moap-final.firebasestorage.app',
    iosBundleId: 'com.example.finalExam',
  );
}
